### ISSUE TITLE
Doesn't see my torrents?

### ISSUE THREAD

**Issue by 097115** [salman-abedin/tide#1]
Hi!

So, I have `transmission-remote` installed, have some torrents added (some are partially downloaded), and `transmission-remote -n 'transmission:transmission' -l` lists them just fine.

Now, as I understand, `tide` should be able to operate to those, right? Or have I misunderstood its purpose completely? :)

However, upon launching, `tide` only shows the [blank screen](https://i.imgur.com/siaJs0g.png). What did I do wrong? :)

**Comment by salman-abedin** [comment]
What is the output you get for `transmission-remote -l`?

**Comment by 097115** [comment]
Aha! Here's the problem:

    Unexpected response: <h1>401: Unauthorized</h1>Unauthorized User

**Comment by salman-abedin** [comment]
See if  you can get around the authentication process. I didn't go to that route as it seemed like an overkill to me.

**Comment by 097115** [comment]
So, you don't use the authentication, do you? The [wiki](https://help.ubuntu.com/community/TransmissionHowTo) says it's required but you somehow disabled it, I understand, right?

**Comment by salman-abedin** [comment]
I've never used it to begin with. I believe there is a version mismatch going on as I am on Arch and you are probably not.
In any case, as far as your fix is concerned, all you have to do is just edit the **ui.c** file and replace `transmission-remote -l` with `transmission-remote -n 'transmission:transmission' -l`

**Comment by 097115** [comment]
Yeah, it works, thanks!

One more question while we are here: I can't edit files to download (like, select only some, edit the selection), can I?

**Comment by salman-abedin** [comment]
I haven't added the feature as of now but you can expect that pretty soon

**Comment by 097115** [comment]
Would be super great :)

Thanks once again!
